import { DatabaseDialect, TargetLanguage } from './types';

type DialectTypeMap = Record<string, string>;
type TargetTypeMaps = Record<TargetLanguage, DialectTypeMap>;

const sqlServerTypeMaps: TargetTypeMaps = {
  csharp: {
    int: 'int',
    bigint: 'long',
    smallint: 'short',
    tinyint: 'byte',
    bit: 'bool',
    boolean: 'bool',
    decimal: 'decimal',
    numeric: 'decimal',
    number: 'decimal',
    float: 'double',
    real: 'float',
    money: 'decimal',
    smallmoney: 'decimal',
    binary: 'byte[]',
    varbinary: 'byte[]',
    image: 'byte[]',
    rowversion: 'byte[]',
    timestamp: 'byte[]',
    uniqueidentifier: 'Guid',
    char: 'string',
    varchar: 'string',
    nchar: 'string',
    nvarchar: 'string',
    xml: 'string',
    sysname: 'string',
    text: 'string',
    ntext: 'string',
    sql_variant: 'string',
    date: 'DateOnly',
    datetime: 'DateTime',
    datetime2: 'DateTime',
    smalldatetime: 'DateTime',
    datetimeoffset: 'DateTimeOffset',
    time: 'TimeSpan',
    json: 'string'
  },
  typescript: {
    int: 'number',
    bigint: 'number',
    smallint: 'number',
    tinyint: 'number',
    bit: 'boolean',
    boolean: 'boolean',
    decimal: 'number',
    numeric: 'number',
    number: 'number',
    float: 'number',
    real: 'number',
    money: 'number',
    smallmoney: 'number',
    binary: 'Uint8Array',
    varbinary: 'Uint8Array',
    image: 'Uint8Array',
    rowversion: 'Uint8Array',
    timestamp: 'Uint8Array',
    uniqueidentifier: 'string',
    char: 'string',
    varchar: 'string',
    nchar: 'string',
    nvarchar: 'string',
    xml: 'string',
    sysname: 'string',
    text: 'string',
    ntext: 'string',
    sql_variant: 'any',
    date: 'string',
    datetime: 'Date',
    datetime2: 'Date',
    smalldatetime: 'Date',
    datetimeoffset: 'Date',
    time: 'string',
    json: 'any'
  },
  json: {},
  python: {
    int: 'int',
    bigint: 'int',
    smallint: 'int',
    tinyint: 'int',
    bit: 'bool',
    boolean: 'bool',
    decimal: 'float',
    numeric: 'float',
    number: 'float',
    float: 'float',
    real: 'float',
    money: 'float',
    smallmoney: 'float',
    binary: 'bytes',
    varbinary: 'bytes',
    image: 'bytes',
    rowversion: 'bytes',
    timestamp: 'bytes',
    uniqueidentifier: 'str',
    char: 'str',
    varchar: 'str',
    nchar: 'str',
    nvarchar: 'str',
    xml: 'str',
    sysname: 'str',
    text: 'str',
    ntext: 'str',
    sql_variant: 'str',
    date: 'date',
    datetime: 'datetime',
    datetime2: 'datetime',
    smalldatetime: 'datetime',
    datetimeoffset: 'datetime',
    time: 'time',
    json: 'dict'
  },
  java: {
    int: 'Integer',
    bigint: 'Long',
    smallint: 'Short',
    tinyint: 'Integer',
    bit: 'Boolean',
    boolean: 'Boolean',
    decimal: 'BigDecimal',
    numeric: 'BigDecimal',
    number: 'BigDecimal',
    float: 'Double',
    real: 'Float',
    money: 'BigDecimal',
    smallmoney: 'BigDecimal',
    binary: 'byte[]',
    varbinary: 'byte[]',
    image: 'byte[]',
    rowversion: 'byte[]',
    timestamp: 'byte[]',
    uniqueidentifier: 'UUID',
    char: 'String',
    varchar: 'String',
    nchar: 'String',
    nvarchar: 'String',
    xml: 'String',
    sysname: 'String',
    text: 'String',
    ntext: 'String',
    sql_variant: 'Object',
    date: 'LocalDate',
    datetime: 'LocalDateTime',
    datetime2: 'LocalDateTime',
    smalldatetime: 'LocalDateTime',
    datetimeoffset: 'OffsetDateTime',
    time: 'LocalTime',
    json: 'Object'
  }
};

const mysqlTypeMaps: TargetTypeMaps = {
  csharp: {
    int: 'int',
    integer: 'int',
    bigint: 'long',
    smallint: 'short',
    tinyint: 'byte',
    mediumint: 'int',
    decimal: 'decimal',
    dec: 'decimal',
    numeric: 'decimal',
    float: 'float',
    double: 'double',
    'double precision': 'double',
    bit: 'bool',
    bool: 'bool',
    boolean: 'bool',
    year: 'int',
    char: 'string',
    varchar: 'string',
    text: 'string',
    tinytext: 'string',
    mediumtext: 'string',
    longtext: 'string',
    enum: 'string',
    set: 'string',
    date: 'DateOnly',
    datetime: 'DateTime',
    timestamp: 'DateTime',
    time: 'TimeSpan',
    json: 'string',
    binary: 'byte[]',
    varbinary: 'byte[]',
    blob: 'byte[]',
    tinyblob: 'byte[]',
    mediumblob: 'byte[]',
    longblob: 'byte[]'
  },
  typescript: {
    int: 'number',
    integer: 'number',
    bigint: 'number',
    smallint: 'number',
    tinyint: 'number',
    mediumint: 'number',
    decimal: 'number',
    dec: 'number',
    numeric: 'number',
    float: 'number',
    double: 'number',
    'double precision': 'number',
    bit: 'boolean',
    bool: 'boolean',
    boolean: 'boolean',
    year: 'number',
    char: 'string',
    varchar: 'string',
    text: 'string',
    tinytext: 'string',
    mediumtext: 'string',
    longtext: 'string',
    enum: 'string',
    set: 'string',
    date: 'string',
    datetime: 'Date',
    timestamp: 'Date',
    time: 'string',
    json: 'any',
    binary: 'Uint8Array',
    varbinary: 'Uint8Array',
    blob: 'Uint8Array',
    tinyblob: 'Uint8Array',
    mediumblob: 'Uint8Array',
    longblob: 'Uint8Array'
  },
  json: {},
  python: {
    int: 'int',
    integer: 'int',
    bigint: 'int',
    smallint: 'int',
    tinyint: 'int',
    mediumint: 'int',
    decimal: 'float',
    dec: 'float',
    numeric: 'float',
    float: 'float',
    double: 'float',
    'double precision': 'float',
    bit: 'bool',
    bool: 'bool',
    boolean: 'bool',
    year: 'int',
    char: 'str',
    varchar: 'str',
    text: 'str',
    tinytext: 'str',
    mediumtext: 'str',
    longtext: 'str',
    enum: 'str',
    set: 'str',
    date: 'date',
    datetime: 'datetime',
    timestamp: 'datetime',
    time: 'time',
    json: 'dict',
    binary: 'bytes',
    varbinary: 'bytes',
    blob: 'bytes',
    tinyblob: 'bytes',
    mediumblob: 'bytes',
    longblob: 'bytes'
  },
  java: {
    int: 'Integer',
    integer: 'Integer',
    bigint: 'Long',
    smallint: 'Short',
    tinyint: 'Integer',
    mediumint: 'Integer',
    decimal: 'BigDecimal',
    dec: 'BigDecimal',
    numeric: 'BigDecimal',
    float: 'Float',
    double: 'Double',
    'double precision': 'Double',
    bit: 'Boolean',
    bool: 'Boolean',
    boolean: 'Boolean',
    year: 'Integer',
    char: 'String',
    varchar: 'String',
    text: 'String',
    tinytext: 'String',
    mediumtext: 'String',
    longtext: 'String',
    enum: 'String',
    set: 'String',
    date: 'LocalDate',
    datetime: 'LocalDateTime',
    timestamp: 'LocalDateTime',
    time: 'LocalTime',
    json: 'Object',
    binary: 'byte[]',
    varbinary: 'byte[]',
    blob: 'byte[]',
    tinyblob: 'byte[]',
    mediumblob: 'byte[]',
    longblob: 'byte[]'
  }
};

const oracleTypeMaps: TargetTypeMaps = {
  csharp: {
    number: 'decimal',
    float: 'double',
    binary_float: 'float',
    binary_double: 'double',
    integer: 'int',
    int: 'int',
    smallint: 'short',
    real: 'float',
    char: 'string',
    nchar: 'string',
    varchar: 'string',
    varchar2: 'string',
    nvarchar2: 'string',
    'character varying': 'string',
    'national character varying': 'string',
    clob: 'string',
    nclob: 'string',
    long: 'string',
    json: 'string',
    date: 'DateTime',
    timestamp: 'DateTime',
    'timestamp with time zone': 'DateTimeOffset',
    'timestamp with local time zone': 'DateTimeOffset',
    interval: 'string',
    raw: 'byte[]',
    'long raw': 'byte[]',
    blob: 'byte[]',
    bfile: 'byte[]'
  },
  typescript: {
    number: 'number',
    float: 'number',
    binary_float: 'number',
    binary_double: 'number',
    integer: 'number',
    int: 'number',
    smallint: 'number',
    real: 'number',
    char: 'string',
    nchar: 'string',
    varchar: 'string',
    varchar2: 'string',
    nvarchar2: 'string',
    'character varying': 'string',
    'national character varying': 'string',
    clob: 'string',
    nclob: 'string',
    long: 'string',
    json: 'any',
    date: 'Date',
    timestamp: 'Date',
    'timestamp with time zone': 'Date',
    'timestamp with local time zone': 'Date',
    interval: 'string',
    raw: 'Uint8Array',
    'long raw': 'Uint8Array',
    blob: 'Uint8Array',
    bfile: 'Uint8Array'
  },
  json: {},
  python: {
    number: 'float',
    float: 'float',
    binary_float: 'float',
    binary_double: 'float',
    integer: 'int',
    int: 'int',
    smallint: 'int',
    real: 'float',
    char: 'str',
    nchar: 'str',
    varchar: 'str',
    varchar2: 'str',
    nvarchar2: 'str',
    'character varying': 'str',
    'national character varying': 'str',
    clob: 'str',
    nclob: 'str',
    long: 'str',
    json: 'dict',
    date: 'datetime',
    timestamp: 'datetime',
    'timestamp with time zone': 'datetime',
    'timestamp with local time zone': 'datetime',
    interval: 'str',
    raw: 'bytes',
    'long raw': 'bytes',
    blob: 'bytes',
    bfile: 'bytes'
  },
  java: {
    number: 'BigDecimal',
    float: 'Double',
    binary_float: 'Float',
    binary_double: 'Double',
    integer: 'Integer',
    int: 'Integer',
    smallint: 'Short',
    real: 'Float',
    char: 'String',
    nchar: 'String',
    varchar: 'String',
    varchar2: 'String',
    nvarchar2: 'String',
    'character varying': 'String',
    'national character varying': 'String',
    clob: 'String',
    nclob: 'String',
    long: 'String',
    json: 'Object',
    date: 'LocalDateTime',
    timestamp: 'LocalDateTime',
    'timestamp with time zone': 'OffsetDateTime',
    'timestamp with local time zone': 'OffsetDateTime',
    interval: 'String',
    raw: 'byte[]',
    'long raw': 'byte[]',
    blob: 'byte[]',
    bfile: 'byte[]'
  }
};

const DIALECT_TYPE_MAPS: Record<DatabaseDialect, TargetTypeMaps> = {
  sqlserver: sqlServerTypeMaps,
  mysql: mysqlTypeMaps,
  oracle: oracleTypeMaps
};

export function getTypeMap(dialect: DatabaseDialect, target: TargetLanguage): DialectTypeMap {
  return DIALECT_TYPE_MAPS[dialect][target];
}
